# Generated by Django 5.0.7 on 2025-03-22 22:05

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DigitRecognitionTrainingData',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('labels', models.CharField(default=None, max_length=1)),
                ('features', models.TextField(default=None)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
            ],
            options={
                'db_table': 'digit_recognition_training_data',
            },
        ),
    ]
