# Generated by Django 5.0.7 on 2025-03-22 23:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('DigitRecognition', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='digitrecognitiontrainingdata',
            old_name='labels',
            new_name='label',
        ),
    ]
